micronaut:
  application:
    name: keymanager

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/keymanager?createDatabaseIfNotExist=TRUE`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Zup123456}
    dialect: MYSQL

jpa.default.properties.hibernate:
  hbm2ddl.auto: update
  show_sql: true
  format_sql: true

logger:
  levels:
    io.micronaut.transactional: DEBUG
    io.micronaut.http.client: DEBUG

# ===> API REST
api_erp_itau: ${API_ERP_ITAU:`http://localhost:9091/api/v1/clientes`}

# ===> Chave de Encriptacao
encryption_key: ${ENCRYPTION_KEY:(4D6Z.qGUWofWm}PxgOhdkQPuA|Y[r!9}

#grpc:
#  client:
#    plaintext: true
#    max-retry-attempts: 10
#  channels:
#    fretes:
#      address: 'localhost:50051'
#      plaintext: true
#      max-retry-attempts: 5